# System
brew "mise"

# Cloud / Infrastructure 
brew "dotenvx/brew/dotenvx", trusted: true
brew "go-task/tap/go-task", trusted: true
brew "pulumi"
brew "graphviz"
brew "copier"
brew "awscli"
cask "session-manager-plugin"
brew "cli53"
brew "helm"
tap "norwoodj/tap"
brew "helm-docs"
brew "k9s"
brew "kubernetes-cli"
tap "terraform-linters/tap", trusted: true
cask "terraform-linters/tap/tflint"
brew "tfsec"
brew "terraform-docs"
brew "infracost"
tap "hashicorp/tap", trusted: true
brew "hashicorp/tap/vault"
brew "podman"
brew "podman-compose"
cask "podman-desktop"
brew "dive"
brew "skopeo"
tap "common-fate/granted"
brew "granted"
brew "fx"
brew "youplot"

# Some dev stuff
brew "pnpm"
brew "poetry"
brew "go"
brew "eslint"
cask "dbeaver-community"
brew "libpq"
cask "sequel-ace"
brew "sonar-scanner"
brew "cloc"
cask "ngrok"
cask "bruno"
brew "ltex-ls"

# Git
brew "lazygit"
brew "git-lfs"
tap "gabrie30/utils", trusted: true
brew "gabrie30/utils/ghorg"
brew "pre-commit"
brew "git-delta"
brew "gh"

# Browsers
cask "firefox"
cask "brave-browser"
cask "google-chrome"

# Fancy terminal utils
cask "font-jetbrains-mono-nerd-font"
cask "wezterm"
brew "bat"
brew "tmux"
brew "tmuxinator"
brew "tree"
brew "diff-so-fancy"
brew "fzf"
brew "fd"
brew "gettext"
brew "jq"
brew "jless"
brew "pandoc"
brew "presenterm"
brew "ripgrep"
brew "stow"
brew "typst"
brew "wget"
brew "zsh"
brew "glow"
brew "httpie"
brew "watch"
brew "starship"
tap "shshemi/homebrew-tabiew"
brew "tabiew"
brew "zsh-vi-mode"
brew "gomplate"
brew "uv"
brew "imagemagick"

# Office & Communication
cask "notion"
cask "slack"
cask "obsidian"

# IDE
brew "tree-sitter-cli"
brew "neovim"

# AI
cask "claude-code"
cask "claude"

# Secrets
cask "1password"
cask "1password-cli"
