#!/bin/bash

PLUGIN_DIR="$CONFIG_DIR/plugins"
ITEM_DIR="$CONFIG_DIR/items"

source "$CONFIG_DIR/variables.sh"

sketchybar --bar height=37        \
                 blur_radius=30   \
                 position=top     \
                 sticky=off       \
                 padding_left=10  \
                 padding_right=10 \
                 color=$BAR_COLOR

default=(
  padding_left=5
  padding_right=5
  icon.font="$FONT:Semibold:14.0"
  label.font="$FONT:Semibold:14.0"
  icon.color=$WHITE
  label.color=$WHITE
  icon.padding_left=10
  icon.padding_right=4
  label.padding_left=10
  label.padding_right=10
  background.color=$ITEM_BG_COLOR
  background.corner_radius=5
  background.height=24
)
sketchybar --default "${default[@]}"

##### Adding Left Items #####

source $ITEM_DIR/spaces.sh

##### Adding Right Items #####

source $ITEM_DIR/calendar.sh
source $ITEM_DIR/volume.sh
source $ITEM_DIR/battery.sh
source $ITEM_DIR/magic_mouse.sh

##### Force all scripts to run the first time (never do this in a script) #####
sketchybar --update
